# Generated by Django 6.0.1 on 2026-03-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0004_add_supplier_to_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparel.supplier'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('po_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='apparel.purchaseorder')),
            ],
        ),
    ]
